### ISSUE TITLE
where can i get a preview picture 

### ISSUE THREAD

**Issue by robinliouhu** [HeliumProject/Helium#71]
1.is this website still working , i can not open it
http://heliumproject.org/wiki/

2.where can i get a preview picture of example and editor ?
   if i can get a pre-build program which can run on windows?

thanks for any help!

**Comment by gorlak** [comment]
1. It is no longer available, where did you see a reference to it?  I can tidy it up

2. What do you mean?  There are no pre-built binaries, this project is still under heavy development.
