### ISSUE TITLE
gdi32.lib is missing building wx

### ISSUE THREAD

**Issue by moonshineTheleocat** [HeliumProject/Helium#73]
```
    link /DLL /NOLOGO /OUT:..\..\lib\vc_x64_dll\wxmsw30ud_vc_custom.dll  /DEBUG /pdb:"..\..\lib\vc_x64_dll\wxmsw30ud_vc_custom.pdb"   /MACHINE:X64 /LIBPATH:..\..\lib\vc_x64_dll   @C:\Users\tangl\AppData\Local\Temp\nm20B9.tmp
```

LINK : fatal error LNK1104: cannot open file 'gdi32.lib'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\BIN\x86_amd64\link.EXE"' : return code '0x450'
Stop.

I'm having some issues trying to build this project on windows 10 using visual studios 2013 (which uses vs2012)

Apparently it's having problems trying to find a library called gdi32.lib

This is trying to build the dependencies

**Comment by gorlak** [comment]
gdi32.lib is a stock Windows Sdk lib.  I use vs2103 without issue at the current time, so I expect this is a local machine confit issue?

Are you building from a vs2013 x64 tools prompt?

-geoff

**Comment by gorlak** [comment]
What do you mean by "which uses vs2012"?  I think that vs2013 support doesn't lean on vs2012 at all, except for maybe some prebuilt p4 libs

**Comment by moonshineTheleocat** [comment]
it reads off as vs2012 x64 Cross tools for me

**Comment by gorlak** [comment]
Then you are using the wrong prompt.  Use the vs2013 x64 native tools command prompt if that is the vstudio version you want to target.
